{
  "headers": {
    "date": "Mon, 11 Apr 2022 04:11:44 GMT",
    "content-type": "application/json; charset=utf-8",
    "content-length": "559",
    "connection": "keep-alive",
    "x-powered-by": "Express",
    "x-ratelimit-limit": "1000",
    "x-ratelimit-remaining": "999",
    "x-ratelimit-reset": "1649650322",
    "vary": "Origin, Accept-Encoding",
    "access-control-allow-credentials": "true",
    "cache-control": "max-age=43200",
    "pragma": "no-cache",
    "expires": "-1",
    "x-content-type-options": "nosniff",
    "etag": "W/\"22f-l/Eoj4zYmvire0cm5iBTWDS+4F8\"",
    "via": "1.1 vegur",
    "cf-cache-status": "MISS",
    "accept-ranges": "bytes",
    "expect-ct": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
    "report-to": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=p7i2s3daHtkDbUzTk1HJ82WFPnPrp0azuxOqF4uV%2BMgFf%2B1oJlsRcBUiD36M1tWIPXg4cT1pJg9vwbagVJG86ZL4Axfv44xPpSJ2Vw6oEvGg%2F2ENcOlaAIjXN7CkXphUP8TctAEigkh1vWl2F6osFL7shA%3D%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
    "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}",
    "server": "cloudflare",
    "cf-ray": "6fa0e13fbc8171d4-LHR",
    "alt-svc": "h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400"
  },
  "reasonPhrase": "OK",
  "statusCode": 200
}