{
  "headers": {
    "date": "Sat, 09 Apr 2022 12:24:37 GMT",
    "content-type": "application/json; charset=utf-8",
    "transfer-encoding": "chunked",
    "connection": "keep-alive",
    "x-powered-by": "Express",
    "x-ratelimit-limit": "1000",
    "x-ratelimit-remaining": "999",
    "x-ratelimit-reset": "1649507026",
    "vary": "Origin, Accept-Encoding",
    "access-control-allow-credentials": "true",
    "cache-control": "max-age=43200",
    "pragma": "no-cache",
    "expires": "-1",
    "x-content-type-options": "nosniff",
    "etag": "W/\"160d-1eMSsxeJRfnVLRBmYJSbCiJZ1qQ\"",
    "via": "1.1 vegur",
    "cf-cache-status": "HIT",
    "age": "94",
    "expect-ct": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
    "report-to": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=3UOaD%2FDHAI93wW4AuPDtXeQcwpq2SwxILATX8Q9w4iYu2s0%2F5asBdXIQkcGMIOMZrNMeJk3WETs%2FkeMwS7BnyxRhD5AC048FfaX8NE9nKpYOMyp7j0rMLrBmwjN%2F3LaGkA0oLolB%2BPj4WJi6D1NTmKiYdQ%3D%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
    "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}",
    "server": "cloudflare",
    "cf-ray": "6f9338856de048fa-SIN",
    "alt-svc": "h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400"
  },
  "reasonPhrase": "OK",
  "statusCode": 200
}