#%RAML 1.0 Library
usage: employ info
types:
  employdatatypes:
    type: object
    properties:
      eno:
        type: integer
        required: false
        example: 123
      ename:
        type: string
        required: true
        example: "testuser"
          
          